spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: employees_test
      username: test
      password: test
      authentication-database: admin

logging:
  level:
    root: INFO
    com.constrsw.employees: DEBUG
    org.springframework.data.mongodb: DEBUG
    org.testcontainers: INFO

